const users = [
  {
    id: 1,
    username: "john_dalls",
    password: "password123",
    name: "John Dallas",
    email: "john@example.com",
    address: "123 Main St, New York, NY 10001",
    phone: "555-123-4567",
    role: "admin",
    status: "active"
  },
  {
    id: 2,
    username: "jane_smith",
    password: "janePass321", 
    name: "Jane Smith",
    email: "jane.smith@example.com",
    address: "456 Elm St, San Francisco, CA 94102",
    phone: "555-987-6543",
    role: "sub admin",
    status: "active"
  },
  {
    id: 3,
    username: "michael_brown",
    password: "mbrown456", 
    name: "Michael Brown",
    email: "michael.brown@example.com",
    address: "789 Maple Ave, Los Angeles, CA 90001",
    phone: "555-222-3333",
    role: "user",
    status: "no active"
  },
  {
    id: 4,
    username: "emily_white",
    password: "emilyW_pass", 
    name: "Emily White",
    email: "emily.white@example.com",
    address: "321 Oak St, Chicago, IL 60601",
    phone: "555-444-5555",
    role: "none user",
    status: "active"
  },
  {
    id: 5,
    username: "adam_jones",
    password: "adamJones789", 
    name: "Adam Jones",
    email: "adam.jones@example.com",
    address: "654 Pine St, Miami, FL 33101",
    phone: "555-666-7777",
    role: "admin",
    status: "active"
  }, {
    id: 6,
    username: "john_doe",
    password: "johnDoe123",
    name: "John Doe",
    email: "john.doe@example.com",
    address: "123 Main St, New York, NY 10001",
    phone: "555-123-4567",
    role: "admin",
    status: "active",
  },
  {
    id: 7,
    username: "jane_smith",
    password: "janeSmith456",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    address: "456 Oak St, San Francisco, CA 94101",
    phone: "555-987-6543",
    role: "subadmin",
    status: "active",
  },
  {
    id: 8,
    username: "michael_lee",
    password: "michaelLee789",
    name: "Michael Lee",
    email: "michael.lee@example.com",
    address: "789 Elm St, Seattle, WA 98101",
    phone: "555-333-8888",
    role: "user",
    status: "inactive",
  },
  {
    id: 9,
    username: "emily_davis",
    password: "emilyDavis123",
    name: "Emily Davis",
    email: "emily.davis@example.com",
    address: "321 Maple St, Chicago, IL 60601",
    phone: "555-444-5555",
    role: "user",
    status: "active",
  },
  {
    id: 10,
    username: "adam_jones",
    password: "adamJones789",
    name: "Adam Jones",
    email: "adam.jones@example.com",
    address: "654 Pine St, Miami, FL 33101",
    phone: "555-666-7777",
    role: "admin",
    status: "active",
  },
  {
    id: 11,
    username: "lisa_wilson",
    password: "lisaWilson456",
    name: "Lisa Wilson",
    email: "lisa.wilson@example.com",
    address: "987 Cedar St, Austin, TX 73301",
    phone: "555-111-2222",
    role: "subadmin",
    status: "inactive",
  },
  {
    id: 12,
    username: "robert_miller",
    password: "robertMiller123",
    name: "Robert Miller",
    email: "robert.miller@example.com",
    address: "654 Birch St, Boston, MA 02101",
    phone: "555-888-9999",
    role: "user",
    status: "active",
  },
  {
    id: 13,
    username: "susan_clark",
    password: "susanClark456",
    name: "Susan Clark",
    email: "susan.clark@example.com",
    address: "432 Walnut St, Denver, CO 80201",
    phone: "555-777-6666",
    role: "none",
    status: "inactive",
  }
];

export default users;
